const I18N_DICTIONARY = {
  ko: {
    nav_about: "소개",
    nav_artists: "아티스트",
    nav_releases: "악보 & 음원",
    nav_tours: "월드투어",
    nav_audition: "플레이리스트",
    nav_news: "뉴스&IR",
    btn_audition: "오디션",
    hero_badge: "차세대 글로벌 K-POP 웨이브",
    hero_title_1: "BEYOND THE",
    hero_desc: "✨ 음악이 머무는 자리, 함께 나누는 마음의 쉼표 🎹 나만의 작은 방에서 건반을 두드리며 곡을 완성해 나갈 때, 일상의 소소한 위로와 따뜻한 온기를 선물하는 음악 공간입니다.",
    hero_btn_roster: "소속 아티스트",
    hero_btn_releases: "최신 릴리즈",
    about_main_title: "✨ 음악이 머무는 자리, 함께 나누는 마음의 쉼표",
    about_intro_1: "🎹 나만의 작은 방에서 건반을 두드리며 곡을 완성해 나갈 때, 또는 일상의 소소한 위로가 필요할 때 조용히 멜로디를 흥얼거릴 때가 있습니다. 그렇게 만들어진 저만의 음악 보물창고를 이제는 세상 밖으로 꺼내어 여러분과 함께 채워가려 합니다.",
    about_intro_2: "🎧 음악은 참 신기한 힘을 가졌어요. 말로는 다 전하지 못하는 복잡한 감정을 가만히 어루만져 주기도 하고, 때로는 낯선 이의 마음과 깊은 곳에서 단번에 연결되기도 하니까요.",
    about_journey_title: "💫 다채로운 음악의 여정",
    journey_piano_title: "클래식 피아노곡",
    journey_piano_desc: "손끝의 미세한 떨림과 깊은 호흡을 담아낸 오리지널 피아노 연주곡입니다. 복잡한 머릿속을 비우고 잔잔한 선율에 깊이 몰입하고 싶을 때 꺼내 듣기 좋아요.",
    journey_vocal_title: "가요",
    journey_vocal_desc: "일상 속에서 문득 스쳐 간 생각과 솔직한 감정들을 가사에 녹여낸 곡들입니다. 누구나 한 번쯤 겪어봤을 법한 이야기들이 담겨 있어요.",
    journey_healing_title: "힐링 플레이리스트",
    journey_healing_desc: "지친 하루 끝에 아무 생각 없이 틀어두기만 해도 마음이 포근해지는 소리들을 모았습니다. 온전한 나만의 휴식을 선물하는 시간이에요.",
    about_outro_1: "🎶 누군가에게는 단 몇 분의 스쳐 지나가는 음악이겠지만, 제 곡을 듣고 잠시나마 미소 짓거나 따뜻한 위안을 얻는다면 그것만으로도 저에게는 더할 나위 없는 큰 기쁨이 될 것 같아요.",
    about_outro_2: "✨ 오늘 저의 플레이리스트가 여러분의 여유로운 시간에 포근한 온기를 더해주는 작은 선물이 되었으면 좋겠습니다. ☕ 여러분은 요즘 어떤 음악으로 일상의 여유를 채우고 계신가요?",
    countdown_title: "D-DAY 카운트다운",
    countdown_days: "일",
    countdown_hours: "시간",
    countdown_mins: "분",
    countdown_secs: "초",
    stat_artists: "전속 아티스트",
    stat_streams: "글로벌 스트리밍",
    stat_tour_audience: "월드투어 누적 관객",
    stat_yt_subs: "유튜브 공식 구독자",
    artists_sub: "소속 라인업",
    artists_title: "사이버",
    artists_title_highlight: "아티스트",
    artists_desc: "Dancing with Angels와 함께 글로벌 트렌드를 주도하는 독보적 아티스트 라인업",
    filter_all: "전체 아티스트",
    filter_pianist: "피아니스트",
    filter_male: "남성 가수",
    filter_female: "여성 가수",
    btn_view_profile: "프로필 & 디스코그래피 보기",
    releases_sub: "Sheet music & Audio (악보 & 음원)",
    releases_title: "",
    releases_title_highlight: "POPULAR TRACKS",
    releases_desc: "전 세계를 매료시킨 Dancing with Angels의 공식 악보 및 고음질 음원 컬렉션",
    tours_sub: "라이브 & 무대",
    tours_title: "월드투어",
    tours_title_highlight: "일정",
    tours_desc: "전 세계 아레나와 스타디움에서 펼쳐지는 생생한 라이브 콘서트",
    tour_status_soldout: "전석 매진",
    tour_status_tickets: "예매 오픈",
    tour_status_coming: "오픈 예정",
    audition_tag: "2026 글로벌 오디션",
    audition_title: "차세대 글로벌",
    audition_title_highlight: "아이콘이 되세요",
    audition_desc: "당신의 숨겨진 열정과 재능으로 세계 무대의 주인공이 되세요. Dancing with Angels가 미래의 글로벌 스타를 찾습니다.",
    nav_playlist: "플레이리스트",
    playlist_sub: "HEALING & MOOD",
    playlist_title: "추천",
    playlist_title_highlight: "플레이리스트 (PLAYLISTS)",
    playlist_desc: "하루의 온도를 포근하게 덥혀주는 감성 피아노와 테마별 힐링 플레이리스트 컬렉션",
    btn_play_playlist: "전체 듣기",
    btn_watch_playlist: "영상 감상",
    field_vocal: "보컬",
    field_dance: "댄스",
    field_rap: "랩",
    field_producer: "프로듀싱",
    btn_apply_audition: "온라인 오디션 지원하기",
    news_sub: "기업 소식 & 미디어",
    news_title: "뉴스 &",
    news_title_highlight: "IR 인사이트",
    news_desc: "댄싱 위드 엔젤스 (천사와춤을)의 주요 경영 소식 및 글로벌 활동 보도자료",
    footer_desc: "(주)댄싱위드엔젤스 (천사와춤을) | 대표이사: Alex Kang & Park Minji<br />서울특별시 강남구 테헤란로 501 엔젤스타워 18F<br />사업자등록번호: 214-88-09123 | 통신판매업신고: 제2026-서울강남-0412호",
    footer_company: "회사소개",
    footer_services: "서비스",
    footer_newsletter: "유튜브 & 뉴스레터",
    footer_newsletter_desc: "공식 유튜브 [천사와춤을] 채널 구독 및 아티스트 컴백 소식을 받아보세요.",
    footer_newsletter_btn: "구독",
    footer_rights: "© 2026 Dancing with Angels CO., LTD. ALL RIGHTS RESERVED.",
    audition_modal_title: "2026 글로벌 오디션 지원",
    audition_modal_subtitle: "차세대 글로벌 K-POP 스타를 향한 당신의 도전을 응원합니다.",
    aud_label_name: "지원자 성명 (Full Name) *",
    aud_label_cat: "지원 분야 (Category) *",
    aud_label_birth: "생년월일 (Birth Date) *",
    aud_label_nat: "국적/거주국가 (Country) *",
    aud_label_email: "이메일 (Email) *",
    aud_label_video: "영상/음원 링크 (YouTube, Drive, Vimeo) *",
    aud_label_intro: "자기소개 및 지원 동기",
    aud_btn_submit: "온라인 지원서 최종 제출"
  },
  en: {
    nav_about: "ABOUT",
    nav_artists: "ARTISTS",
    nav_releases: "Sheet music & Audio",
    nav_tours: "WORLD TOUR",
    nav_audition: "Playlist",
    nav_news: "NEWS & IR",
    btn_audition: "AUDITION",
    hero_badge: "NEXT GENERATION K-POP WAVE",
    hero_title_1: "BEYOND THE",
    hero_desc: "✨ A Sanctuary of Music, A Peaceful Pause for the Soul 🎹 Crafting original melodies with warm emotions, bringing gentle solace to your everyday life.",
    hero_btn_roster: "ARTIST ROSTER",
    hero_btn_releases: "LATEST RELEASES",
    about_main_title: "✨ Where Music Resides, A Gentle Pause for the Soul",
    about_intro_1: "🎹 In the quiet of my room, touching the piano keys to compose melodies or humming tunes when in need of solace—this private treasure trove of music is now shared with you.",
    about_intro_2: "🎧 Music possesses a magical force. It comforts intricate emotions beyond words and connects hearts across distant souls in an instant.",
    about_journey_title: "💫 A Diverse Musical Odyssey",
    journey_piano_title: "Classical Piano Solo",
    journey_piano_desc: "Original piano compositions capturing subtle touches and deep breaths. Perfect for clearing your mind and immersing in gentle harmonies.",
    journey_vocal_title: "Vocal & K-Pop",
    journey_vocal_desc: "Songs with heartfelt lyrics reflecting everyday thoughts and sincere emotions that everyone can relate to.",
    journey_healing_title: "Healing Playlist",
    journey_healing_desc: "A soothing collection of calming sounds to unwind at the end of an exhausting day, offering pure relaxation.",
    about_outro_1: "🎶 Even if it is just a passing moment, if my music brings you a warm smile or gentle comfort, that is my greatest joy.",
    about_outro_2: "✨ May today's playlist be a warm gift to your relaxing hours. ☕ What melodies are filling your peaceful moments today?",
    countdown_title: "D-DAY COUNTDOWN",
    countdown_days: "DAYS",
    countdown_hours: "HOURS",
    countdown_mins: "MINS",
    countdown_secs: "SECS",
    stat_artists: "EXCLUSIVE ARTISTS",
    stat_streams: "GLOBAL STREAMS",
    stat_tour_audience: "WORLD TOUR ATTENDEES",
    stat_yt_subs: "YOUTUBE SUBSCRIBERS",
    artists_sub: "EXCLUSIVE ROSTER",
    artists_title: "CYBER",
    artists_title_highlight: "ARTISTS",
    artists_desc: "Unrivaled artist roster shaping global trends with Dancing with Angels",
    filter_all: "ALL ARTISTS",
    filter_pianist: "PIANIST",
    filter_male: "MALE ARTIST",
    filter_female: "FEMALE ARTIST",
    btn_view_profile: "VIEW PROFILE & DISCOGRAPHY",
    releases_sub: "Sheet music & Audio",
    releases_title: "",
    releases_title_highlight: "POPULAR TRACKS",
    releases_desc: "Chart-topping tracks and official piano sheet music from Dancing with Angels",
    tours_sub: "LIVE & STAGE",
    tours_title: "WORLD TOUR",
    tours_title_highlight: "SCHEDULE",
    tours_desc: "Electrifying live performances across world-class stadiums and arenas",
    tour_status_soldout: "SOLD OUT",
    tour_status_tickets: "TICKETS OPEN",
    tour_status_coming: "COMING SOON",
    audition_tag: "2026 GLOBAL SEARCH",
    audition_title: "BE THE NEXT",
    audition_title_highlight: "GLOBAL ICON",
    audition_desc: "Unleash your passion and step into the global spotlight. Dancing with Angels is discovering future icons.",
    nav_playlist: "Playlist",
    playlist_sub: "HEALING & MOOD",
    playlist_title: "CURATED",
    playlist_title_highlight: "PLAYLISTS",
    playlist_desc: "Emotive piano melodies and themed healing playlists crafted to elevate your daily moments",
    btn_play_playlist: "PLAY ALL",
    btn_watch_playlist: "WATCH VIDEO",
    field_vocal: "VOCAL",
    field_dance: "DANCE",
    field_rap: "RAP",
    field_producer: "PRODUCER",
    btn_apply_audition: "ONLINE AUDITION APPLY",
    news_sub: "COMPANY & MEDIA",
    news_title: "NEWS &",
    news_title_highlight: "IR INSIGHTS",
    news_desc: "Official press releases and strategic business updates from Dancing with Angels",
    footer_desc: "Dancing with Angels CO., LTD. | CEO: Alex Kang & Minji Park<br />18F Angels Tower, 501 Teheran-ro, Gangnam-gu, Seoul, Korea / Los Angeles, USA<br />Business Reg: 214-88-09123",
    footer_company: "COMPANY",
    footer_services: "SERVICES",
    footer_newsletter: "YOUTUBE & NEWSLETTER",
    footer_newsletter_desc: "Subscribe to official YouTube [천사와춤을] & get instant comeback alerts.",
    footer_newsletter_btn: "SUBSCRIBE",
    footer_rights: "© 2026 Dancing with Angels CO., LTD. ALL RIGHTS RESERVED.",
    audition_modal_title: "2026 GLOBAL AUDITION APPLY",
    audition_modal_subtitle: "Your journey to becoming a global icon starts here.",
    aud_label_name: "Full Name *",
    aud_label_cat: "Audition Category *",
    aud_label_birth: "Birth Date *",
    aud_label_nat: "Country / Nationality *",
    aud_label_email: "Email Address *",
    aud_label_video: "Video / Audio Link (YouTube, Drive, etc.) *",
    aud_label_intro: "Self Introduction & Motivation",
    aud_btn_submit: "SUBMIT APPLICATION"
  }
};

const NOVA_DATA = {
  company: {
    name: "Dancing with Angels",
    krName: "댄싱 위드 엔젤스 (천사와춤을)",
    slogan: "BEYOND THE UNIVERSE, THE NEXT BEAT OF MUSIC",
    description: "글로벌 음악 시장의 새로운 지평을 여는 크리에이티브 레이블",
    founded: "2021",
    ceo: "Alex Kang & Minji Park",
    headquarters: "Seoul, Republic of Korea / Los Angeles, USA",
    stockTicker: "KRX: 389250 (ANGELS ENT)",
    stats: {
      artists: 6,
      globalStreams: "12.8B+",
      worldTourAudience: "3.4M+",
      youtubeSubscribers: "45M+"
    }
  },

  // 컴백 D-DAY 하이라이트
  featuredComeback: {
    artist: "Sang-hoon's Piano",
    channelName: "천사와춤을",
    title: "SUPERNOVA ODYSSEY",
    type: "The 3rd Mini Album",
    releaseDate: "2026.09.15 18:00 KST",
    targetTimestamp: new Date(Date.now() + 16 * 24 * 60 * 60 * 1000 + 4 * 60 * 60 * 1000).toISOString(),
    teaserVideoUrl: "https://www.youtube-nocookie.com/embed/UF528KwJ5Io?autoplay=1&mute=0&rel=0",
    watchUrl: "https://www.youtube.com/watch?v=UF528KwJ5Io&list=RDMMUF528KwJ5Io&index=1",
    conceptImage: "https://img.youtube.com/vi/UF528KwJ5Io/maxresdefault.jpg",
    fallbackImage: "https://img.youtube.com/vi/UF528KwJ5Io/hqdefault.jpg",
    description: "경계를 허무는 강렬한 퓨처리스틱 사운드와 비비드한 비주얼 아트워크의 정점."
  },

  // 아티스트 목록
  artists: [
    {
      id: "alex-piano",
      name: "ALEX K",
      krName: "알렉스 케이",
      category: "pianist",
      debut: "2019.05.20",
      members: ["알렉스 케이(Alex K)"],
      enMembers: ["Alex K"],
      concept: "Neo-Classical / Cinematic Piano",
      fandom: "HARMONY",
      image: "images/alex_k_portrait.jpg",
      coverImage: "images/alex_k_cover.jpg",
      badge: "MAESTRO PIANIST",
      bio: "손끝에서 피어나는 깊은 서사와 웅장한 선율로 전 세계 클래식 & 영화 음악 팬들을 사로잡은 감성 피아니스트.",
      enBio: "A visionary maestro who captivates global classical and cinematic music enthusiasts with profound narratives and breathtaking melodies born from his fingertips.",
      spotifyUrl: "#",
      youtubeUrl: "https://www.youtube.com/watch?v=pKtkKWE8EEM&list=PLIFlATW5erkc&index=4",
      instagramUrl: "#",
      topTracks: [
        { 
          title: "Sunday Slow Motion", 
          album: "Piano Journal", 
          plays: "420M",
          sheetPdf: "sheet music/1-Sunday Slow Motion/Sunday Slow Motion.pdf",
          audioSrc: "sheet music/1-Sunday Slow Motion/Sunday Slow Motion.mp3"
        },
        { 
          title: "Watercolor Bus Stop", 
          album: "Piano Journal", 
          plays: "380M",
          sheetPdf: "sheet music/2-Watercolor Bus Stop/Watercolor Bus Stop.pdf",
          audioSrc: "sheet music/2-Watercolor Bus Stop/Watercolor Bus Stop.mp3"
        },
        { 
          title: "Symphony of the Cold Brew", 
          album: "Memories", 
          plays: "290M",
          sheetPdf: "sheet music/3-Symphony of the Cold Brew/Symphony of the Cold Brew.pdf",
          audioSrc: "sheet music/3-Symphony of the Cold Brew/Symphony of the Cold Brew.mp3"
        }
      ]
    },
    {
      id: "sanghoon-kim",
      name: "Sanghoon, Kim.",
      krName: "김상훈",
      category: "pianist",
      debut: "2021.03.15",
      members: ["김상훈(Sanghoon Kim)"],
      enMembers: ["Sanghoon Kim"],
      concept: "Ambient & Healing Piano Solo",
      fandom: "CALM WAVE",
      image: "images/Sanghoon-Kim1.jpg",
      coverImage: "https://images.unsplash.com/photo-1514119412350-e174d90d280e?q=80&w=1200&auto=format&fit=crop",
      badge: "HEALING PIANIST",
      bio: "손끝의 섬세한 터치와 깊은 호흡으로 일상에 잔잔한 휴식과 따뜻한 감동을 전하는 감성 피아니스트.",
      enBio: "An emotive pianist who delivers serene solace and heartwarming resonance to everyday life through delicate touch and profound musical depth.",
      spotifyUrl: "#",
      youtubeUrl: "https://www.youtube.com/watch?v=UF528KwJ5Io&list=PLIFlATW5erkc&index=2",
      instagramUrl: "#",
      topTracks: [
        { 
          title: "Saturday Motion", 
          album: "Quiet Sunlight", 
          plays: "210M",
          sheetPdf: "sheet music/4-Saturday Motion/Saturday Motion.pdf",
          audioSrc: "sheet music/4-Saturday Motion/Saturday Motion.mp3"
        },
        { 
          title: "Lazy Saturday Suns", 
          album: "Quiet Sunlight", 
          plays: "195M",
          sheetPdf: "sheet music/5-Lazy Saturday Suns/Lazy Saturday Suns.pdf",
          audioSrc: "sheet music/5-Lazy Saturday Suns/Lazy Saturday Suns.mp3"
        }
      ]
    },
    {
      id: "vivid9",
      name: "VIVID9",
      krName: "비비드나인",
      category: "female",
      debut: "2023.05.02",
      members: ["루나(Luna)", "시아(Sia)", "민서(Minseo)", "유키(Yuki)", "에블린(Evelyn)"],
      enMembers: ["Luna", "Sia", "Minseo", "Yuki", "Evelyn"],
      concept: "Neo-Pop / Cyberpunk Chic",
      fandom: "VIVID LIGHT",
      image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=800&auto=format&fit=crop",
      coverImage: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?q=80&w=1200&auto=format&fit=crop",
      badge: "HOT COMEBACK",
      bio: "다채로운 스펙트럼의 비주얼과 압도적인 퍼포먼스로 빌보드 글로벌 200 최상위권에 진입한 5인조 여성 그룹.",
      enBio: "A groundbreaking 5-member girl group dominating the Billboard Global 200 with an electrifying visual spectrum and overwhelming performance prowess.",
      spotifyUrl: "#",
      youtubeUrl: "#",
      instagramUrl: "#",
      topTracks: [
        { title: "Prism Heart", album: "Spectrum", plays: "340M" },
        { title: "Neon Velocity", album: "Spectrum", plays: "210M" },
        { title: "Eclipse Mind", album: "Dawn", plays: "185M" }
      ]
    },
    {
      id: "lumen",
      name: "LUMEN",
      krName: "루멘",
      category: "male",
      debut: "2022.11.18",
      members: ["도현(Dohyun)", "태오(Taeo)", "제이든(Jayden)", "카이(Kai)", "로운(Rowoon)", "진우(Jinwoo)", "리쿠(Riku)"],
      enMembers: ["Dohyun", "Taeo", "Jayden", "Kai", "Rowoon", "Jinwoo", "Riku"],
      concept: "Hyper-Performance / Dark Fantasy",
      fandom: "LUMINARY",
      image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=800&auto=format&fit=crop",
      coverImage: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?q=80&w=1200&auto=format&fit=crop",
      badge: "STADIUM TOUR",
      bio: "폭발적인 에너제틱 군무와 웅장한 세계관 스토리텔링으로 전 세계 아레나를 달구는 7인조 남성 그룹.",
      enBio: "A powerhouse 7-member boy group igniting global arenas with explosive synchronized choreography and epic universe storytelling.",
      spotifyUrl: "#",
      youtubeUrl: "#",
      instagramUrl: "#",
      topTracks: [
        { title: "Shadow Horizon", album: "ECLIPSE", plays: "520M" },
        { title: "Ignition Beat", album: "ECLIPSE", plays: "410M" },
        { title: "Eternal Flame", album: "Genesis", plays: "330M" }
      ]
    },
    {
      id: "nexus",
      name: "NEXUS",
      krName: "넥서스",
      category: "male",
      debut: "2024.03.10",
      members: ["시우(Siwoo)", "한결(Hangyul)", "노아(Noah)", "에릭(Eric)"],
      enMembers: ["Siwoo", "Hangyul", "Noah", "Eric"],
      concept: "Alternative Hip-Hop / Street Y2K",
      fandom: "NEXTGEN",
      image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=800&auto=format&fit=crop",
      coverImage: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=1200&auto=format&fit=crop",
      badge: "ROOKIE OF THE YEAR",
      bio: "전원 자체 프로듀싱 능력을 갖춘 4인조 남성 힙합 유닛. 감각적인 비트와 트렌디한 감성으로 Z세대를 매료.",
      enBio: "A self-producing 4-member hip-hop unit captivating Gen Z worldwide through infectious grooves, avant-garde beats, and authentic street sensibility.",
      spotifyUrl: "#",
      youtubeUrl: "#",
      instagramUrl: "#",
      topTracks: [
        { title: "Overdrive", album: "Code:Red", plays: "120M" },
        { title: "City Lights", album: "Code:Red", plays: "95M" }
      ]
    },
    {
      id: "stella",
      name: "STELLA-X",
      krName: "스텔라엑스",
      category: "female",
      debut: "2024.08.20",
      members: ["아이린(Irene)", "지수(Jisoo)", "미야(Miya)", "소피아(Sophia)"],
      enMembers: ["Irene", "Jisoo", "Miya", "Sophia"],
      concept: "Ethereal Dream-Pop & Hyper-Future",
      fandom: "STARDUST",
      image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=800&auto=format&fit=crop",
      coverImage: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=1200&auto=format&fit=crop",
      badge: "GLOBAL TOP 10",
      bio: "몽환적인 멜로디와 독보적인 음색의 조화, 버추얼과 리얼리티를 넘나드는 차세대 4인조 여성 그룹.",
      enBio: "A next-generation 4-member girl group seamlessly transcending virtuality and reality with ethereal dream-pop melodies and hypnotic vocal colors.",
      spotifyUrl: "#",
      youtubeUrl: "#",
      instagramUrl: "#",
      topTracks: [
        { title: "Cosmic Gravity", album: "Milkyway", plays: "98M" },
        { title: "Velvet Sky", album: "Milkyway", plays: "82M" }
      ]
    },
    {
      id: "kairos",
      name: "KAIROS",
      krName: "카이로스",
      category: "male",
      debut: "2020.09.14",
      members: ["강민(Kangmin)"],
      enMembers: ["Kangmin"],
      concept: "R&B / Soul / Modern Pop",
      fandom: "CHRONOS",
      image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=800&auto=format&fit=crop",
      coverImage: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=1200&auto=format&fit=crop",
      badge: "PLATINUM ARTIST",
      bio: "독보적인 그루브와 섬세한 보컬 테크닉으로 수많은 음원 차트 1위를 휩쓴 대한민국 대표 남성 솔로 아티스트이자 프로듀서.",
      enBio: "A premier male solo artist and visionary producer dominating global charts with soulful grooves, intricate vocal dynamics, and modern pop artistry.",
      spotifyUrl: "#",
      youtubeUrl: "#",
      instagramUrl: "#",
      topTracks: [
        { title: "Midnight Avenue", album: "Blue Hour", plays: "460M" },
        { title: "Echoes in the Rain", album: "Blue Hour", plays: "310M" }
      ]
    },
    {
      id: "rea",
      name: "REA",
      krName: "리아",
      category: "female",
      debut: "2021.04.12",
      members: ["리아 박(Rea Park)"],
      enMembers: ["Rea Park"],
      concept: "Dance Diva / Electronic Pop",
      fandom: "REALITY",
      image: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=800&auto=format&fit=crop",
      coverImage: "https://images.unsplash.com/photo-1469488865564-c2de10f69f96?q=80&w=1200&auto=format&fit=crop",
      badge: "QUEEN OF STAGE",
      bio: "카리스마 넘치는 퍼포먼스와 한계 없는 음악적 스펙트럼을 자랑하는 독보적 글로벌 여성 솔로 디바.",
      enBio: "An unrivaled global dance diva renowned for her magnetic stage presence, powerhouse vocals, and boundless musical range.",
      spotifyUrl: "#",
      youtubeUrl: "#",
      instagramUrl: "#",
      topTracks: [
        { title: "Venom Kiss", album: "Sirens", plays: "280M" },
        { title: "Golden Hour", album: "Sirens", plays: "240M" }
      ]
    }
  ],

  // 최신 악보 & 음원 릴리즈 (Sheet music & Audio)
  releases: [
    {
      id: "sheet-1",
      no: "1",
      title: "Sunday Slow Motion",
      album: "Piano Journal",
      artist: "ALEX K",
      plays: "420M",
      sheetPdf: "sheet music/1-Sunday Slow Motion/Sunday Slow Motion.pdf",
      audioSrc: "sheet music/1-Sunday Slow Motion/Sunday Slow Motion.mp3"
    },
    {
      id: "sheet-2",
      no: "2",
      title: "Watercolor Bus Stop",
      album: "Piano Journal",
      artist: "ALEX K",
      plays: "380M",
      sheetPdf: "sheet music/2-Watercolor Bus Stop/Watercolor Bus Stop.pdf",
      audioSrc: "sheet music/2-Watercolor Bus Stop/Watercolor Bus Stop.mp3"
    },
    {
      id: "sheet-3",
      no: "3",
      title: "Symphony of the Cold Brew",
      album: "Memories",
      artist: "ALEX K",
      plays: "290M",
      sheetPdf: "sheet music/3-Symphony of the Cold Brew/Symphony of the Cold Brew.pdf",
      audioSrc: "sheet music/3-Symphony of the Cold Brew/Symphony of the Cold Brew.mp3"
    },
    {
      id: "sheet-4",
      no: "4",
      title: "Saturday Motion",
      album: "Quiet Sunlight",
      artist: "Sanghoon, Kim.",
      plays: "210M",
      sheetPdf: "sheet music/4-Saturday Motion/Saturday Motion.pdf",
      audioSrc: "sheet music/4-Saturday Motion/Saturday Motion.mp3"
    },
    {
      id: "sheet-5",
      no: "5",
      title: "Lazy Saturday Suns",
      album: "Quiet Sunlight",
      artist: "Sanghoon, Kim.",
      plays: "195M",
      sheetPdf: "sheet music/5-Lazy Saturday Suns/Lazy Saturday Suns.pdf",
      audioSrc: "sheet music/5-Lazy Saturday Suns/Lazy Saturday Suns.mp3"
    }
  ],

  // 월드 투어 일정
  worldTours: [
    {
      id: "tour-1",
      artist: "LUMEN",
      tourName: "2026 LUMEN WORLD TOUR <HORIZON>",
      city: "Seoul, Korea",
      venue: "KSPO DOME",
      date: "2026.10.10 - 10.12",
      status: "SOLD OUT",
      statusClass: "badge-soldout"
    },
    {
      id: "tour-2",
      artist: "LUMEN",
      tourName: "2026 LUMEN WORLD TOUR <HORIZON>",
      city: "Tokyo, Japan",
      venue: "Tokyo Dome",
      date: "2026.10.24 - 10.25",
      status: "SOLD OUT",
      statusClass: "badge-soldout"
    },
    {
      id: "tour-3",
      artist: "VIVID9",
      tourName: "VIVID9 1st GLOBAL TOUR <SPECTRUM: LIVE>",
      city: "Los Angeles, USA",
      venue: "Crypto.com Arena",
      date: "2026.11.08",
      status: "TICKETS OPEN",
      statusClass: "badge-active"
    },
    {
      id: "tour-4",
      artist: "VIVID9",
      tourName: "VIVID9 1st GLOBAL TOUR <SPECTRUM: LIVE>",
      city: "London, UK",
      venue: "The O2 Arena",
      date: "2026.11.20",
      status: "TICKETS OPEN",
      statusClass: "badge-active"
    },
    {
      id: "tour-5",
      artist: "KAIROS",
      tourName: "KAIROS LIVE CONCERT <BLUE HOUR>",
      city: "Paris, France",
      venue: "Accor Arena",
      date: "2026.12.05",
      status: "COMING SOON",
      statusClass: "badge-pending"
    },
    {
      id: "tour-6",
      artist: "NEXUS",
      tourName: "NEXUS SHOWCASE TOUR <OVERDRIVE>",
      city: "Bangkok, Thailand",
      venue: "Impact Arena",
      date: "2026.12.18",
      status: "COMING SOON",
      statusClass: "badge-pending"
    }
  ],

  // 뉴스 & 보도자료
  news: [
    {
      id: "news-1",
      category: "PRESS RELEASE",
      title: "VIVID9 미니 3집 'SUPERNOVA ODYSSEY' 선주문 150만 장 돌파… 자체 신기록 경신",
      enTitle: "VIVID9 3rd Mini Album 'SUPERNOVA ODYSSEY' Exceeds 1.5M Pre-orders",
      date: "2026.08.28",
      summary: "차세대 글로벌 대표 걸그룹 비비드나인의 신보가 발매 전부터 글로벌 선주문량 150만 장을 돌파하며 밀리언셀러 예고.",
      enSummary: "VIVID9 sets an all-time record with over 1.5 million worldwide pre-orders ahead of release.",
      image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?q=80&w=600&auto=format&fit=crop"
    },
    {
      id: "news-2",
      category: "IR & BUSINESS",
      title: "Dancing with Angels, 2026년 상반기 연결 매출 3,200억 원 달성… 글로벌 스트리밍 호조",
      enTitle: "Dancing with Angels Records KRW 320 Billion in 1H 2026 Revenue on Global Boom",
      date: "2026.08.15",
      summary: "공식 악보 및 오리지널 피아노 음원의 전 세계 스트리밍 매출 다각화로 전년 동기 대비 영업이익 48% 상승.",
      enSummary: "Operating profit jumps 48% YoY driven by massive sheet music distribution and global acoustic streaming.",
      image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=600&auto=format&fit=crop"
    },
    {
      id: "news-3",
      category: "NEW RELEASE",
      title: "Dancing with Angels 오리지널 피아노 악보집 출간 및 온라인 악보 서비스 오픈",
      enTitle: "Dancing with Angels Official Piano Sheet Music Collection & Online Viewer Released",
      date: "2026.08.01",
      summary: "Sunday Slow Motion을 비롯한 주요 명곡들의 고화질 악보 PDF와 고음질 음원 스트리밍 서비스 런칭.",
      enSummary: "High-definition sheet music PDFs and lossless audio streaming officially launched worldwide.",
      image: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=600&auto=format&fit=crop"
    }
  ],

  // 테마별 추천 플레이리스트 (Curated Playlists)
  playlists: [
    {
      id: "pl-1",
      title: "Sunday Slow Morning",
      enTitle: "Sunday Slow Morning",
      desc: "따스한 햇살 아래, 커피 한 잔과 함께 듣는 여유로운 주말 힐링 피아노 선율",
      enDesc: "Peaceful weekend piano melodies bathed in warm sunlight, perfect with a warm cup of coffee",
      badge: "HEALING PIANO",
      tracksCount: "10 TRACKS · 42 MIN",
      cover: "images/playlist_korean_nature1.jpg",
      primaryTrackTitle: "Sunday Slow Motion",
      primaryTrackArtist: "ALEX K",
      audioSrc: "sheet music/1-Sunday Slow Motion/Sunday Slow Motion.mp3",
      youtubeUrl: "https://www.youtube.com/watch?v=pKtkKWE8EEM&list=PLIFlATW5erkc&index=4"
    },
    {
      id: "pl-2",
      title: "Watercolor Bus Stop",
      enTitle: "Watercolor Bus Stop",
      desc: "촉촉한 빗방울 소리와 투명한 수채화처럼 번지는 감성 연주곡",
      enDesc: "Soft raindrops on window panes and transparent watercolor emotions in gentle harmony",
      badge: "WATERCOLOR MOOD",
      tracksCount: "8 TRACKS · 35 MIN",
      cover: "images/playlist_korean_nature2.jpg",
      primaryTrackTitle: "Watercolor Bus Stop",
      primaryTrackArtist: "ALEX K",
      audioSrc: "sheet music/2-Watercolor Bus Stop/Watercolor Bus Stop.mp3",
      youtubeUrl: "https://www.youtube.com/watch?v=EAy7jr297CQ&list=PLIFlATW5erkc&index=5"
    },
    {
      id: "pl-3",
      title: "Symphony of the Cold Brew",
      enTitle: "Symphony of the Cold Brew",
      desc: "집중과 사색이 필요한 순간, 머릿속을 맑게 비워주는 미니멀 클래식",
      enDesc: "Deep and subtle piano harmonies that clear your mind for deep focus, reading, and contemplation",
      badge: "STUDY & FOCUS",
      tracksCount: "12 TRACKS · 50 MIN",
      cover: "images/playlist_korean_nature3.jpg",
      primaryTrackTitle: "Symphony of the Cold Brew",
      primaryTrackArtist: "ALEX K",
      audioSrc: "sheet music/3-Symphony of the Cold Brew/Symphony of the Cold Brew.mp3",
      youtubeUrl: "https://www.youtube.com/watch?v=8s1n_NcVU-U&list=PLIFlATW5erkc&index=1"
    },
    {
      id: "pl-4",
      title: "Lazy Saturday Suns",
      enTitle: "Lazy Saturday Suns",
      desc: "나른하고 평화로운 토요일의 햇살처럼 지친 마음을 가만히 감싸 안아주는 선율",
      enDesc: "A peaceful lazy Saturday melody that gently comforts your soul with warm ambient sunlight",
      badge: "LAZY & RELAX",
      tracksCount: "9 TRACKS · 38 MIN",
      cover: "images/playlist_lazy_saturday_suns.jpg",
      primaryTrackTitle: "Lazy Saturday Suns",
      primaryTrackArtist: "Sanghoon, Kim.",
      audioSrc: "sheet music/5-Lazy Saturday Suns/Lazy Saturday Suns.mp3",
      youtubeUrl: "https://www.youtube.com/watch?v=90ze-T_UyKI&list=PLIFlATW5erkc&index=3"
    }
  ]
};

if (typeof window !== "undefined") {
  window.NOVA_DATA = NOVA_DATA;
  window.I18N_DICTIONARY = I18N_DICTIONARY;
}
